! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Parameters.f90
! Time                 : Sun Jun 28 17:51:27 2020
! Working directory    : /n/home02/thackray/GC_working/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 35 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 18 
! NFLUX - Number of Reaction Flux species
  INTEGER, PARAMETER :: NFLUX = 1 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 1 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 17 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 17 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 64 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 19 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 86 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 92 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 19 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_PHg = 1 
  INTEGER, PARAMETER :: ind_HGBRNO2 = 2 
  INTEGER, PARAMETER :: ind_HGBRHO2 = 3 
  INTEGER, PARAMETER :: ind_HGBRCLO = 4 
  INTEGER, PARAMETER :: ind_HGBRBRO = 5 
  INTEGER, PARAMETER :: ind_HGBR2 = 6 
  INTEGER, PARAMETER :: ind_HGBROH = 7 
  INTEGER, PARAMETER :: ind_HGBR = 8 
  INTEGER, PARAMETER :: ind_HGCLNO2 = 9 
  INTEGER, PARAMETER :: ind_HGCLHO2 = 10 
  INTEGER, PARAMETER :: ind_HGCLCLO = 11 
  INTEGER, PARAMETER :: ind_HGCLBRO = 12 
  INTEGER, PARAMETER :: ind_HGCLBR = 13 
  INTEGER, PARAMETER :: ind_HGCLOH = 14 
  INTEGER, PARAMETER :: ind_HGCL = 15 
  INTEGER, PARAMETER :: ind_HGORG = 16 
  INTEGER, PARAMETER :: ind_HgP = 17 
  INTEGER, PARAMETER :: ind_Hg0 = 18 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_Br = 19 
  INTEGER, PARAMETER :: ind_Cl = 20 
  INTEGER, PARAMETER :: ind_OH = 21 
  INTEGER, PARAMETER :: ind_NO2 = 22 
  INTEGER, PARAMETER :: ind_HO2 = 23 
  INTEGER, PARAMETER :: ind_BrO = 24 
  INTEGER, PARAMETER :: ind_ClO = 25 
  INTEGER, PARAMETER :: ind_JHGCLOH = 26 
  INTEGER, PARAMETER :: ind_JHGBR = 27 
  INTEGER, PARAMETER :: ind_JHGAQ = 28 
  INTEGER, PARAMETER :: ind_O3 = 29 
  INTEGER, PARAMETER :: ind_SO4 = 30 
  INTEGER, PARAMETER :: ind_BCPI = 31 
  INTEGER, PARAMETER :: ind_POA1 = 32 
  INTEGER, PARAMETER :: ind_OCPI = 33 
  INTEGER, PARAMETER :: ind_SALA = 34 
  INTEGER, PARAMETER :: ind_SALC = 35 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_Br = 1 
  INTEGER, PARAMETER :: indf_Cl = 2 
  INTEGER, PARAMETER :: indf_OH = 3 
  INTEGER, PARAMETER :: indf_NO2 = 4 
  INTEGER, PARAMETER :: indf_HO2 = 5 
  INTEGER, PARAMETER :: indf_BrO = 6 
  INTEGER, PARAMETER :: indf_ClO = 7 
  INTEGER, PARAMETER :: indf_JHGCLOH = 8 
  INTEGER, PARAMETER :: indf_JHGBR = 9 
  INTEGER, PARAMETER :: indf_JHGAQ = 10 
  INTEGER, PARAMETER :: indf_O3 = 11 
  INTEGER, PARAMETER :: indf_SO4 = 12 
  INTEGER, PARAMETER :: indf_BCPI = 13 
  INTEGER, PARAMETER :: indf_POA1 = 14 
  INTEGER, PARAMETER :: indf_OCPI = 15 
  INTEGER, PARAMETER :: indf_SALA = 16 
  INTEGER, PARAMETER :: indf_SALC = 17 

END MODULE gckpp_Parameters

