! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Function of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Function.f90
! Time                 : Mon Jun 15 15:13:47 2020
! Working directory    : /n/home02/thackray/GC_working/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Function

  USE gckpp_Parameters
  IMPLICIT NONE

! A - Rate for each equation
  REAL(kind=dp) :: A(NREACT)
!$OMP THREADPRIVATE(  A )

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Fun - time derivatives of variables - Agregate form
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      Vdot      - Time derivative of variable species concentrations
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Fun ( V, F, RCT, Vdot, Aout )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! Vdot - Time derivative of variable species concentrations
  REAL(kind=dp) :: Vdot(NVAR)


  REAL(dp), optional :: Aout(NREACT)

! Computation of equation rates
  A(1) = RCT(1)*V(18)*F(1)
  A(2) = RCT(2)*V(8)
  A(3) = RCT(3)*V(8)*F(1)
  A(4) = RCT(4)*V(8)*F(4)
  A(5) = RCT(5)*V(8)*F(5)
  A(6) = RCT(6)*V(8)*F(7)
  A(7) = RCT(7)*V(8)*F(6)
  A(8) = RCT(8)*V(8)*F(1)
  A(9) = RCT(9)*V(8)*F(3)
  A(10) = RCT(10)*V(8)*F(13)
  A(11) = RCT(11)*V(2)*F(9)
  A(12) = RCT(12)*V(3)*F(8)
  A(13) = RCT(13)*V(7)*F(10)
  A(14) = RCT(14)*V(6)*F(10)
  A(15) = RCT(15)*V(5)*F(11)
  A(16) = RCT(16)*V(4)*F(11)
  A(17) = RCT(17)*V(18)*F(2)
  A(18) = RCT(18)*V(15)*F(2)
  A(19) = RCT(19)*V(15)*F(4)
  A(20) = RCT(20)*V(15)*F(5)
  A(21) = RCT(21)*V(15)*F(7)
  A(22) = RCT(22)*V(15)*F(6)
  A(23) = RCT(23)*V(15)*F(1)
  A(24) = RCT(24)*V(15)*F(3)
  A(25) = RCT(25)*V(14)*F(12)
  A(26) = RCT(26)*V(10)*F(12)
  A(27) = RCT(27)*V(9)*F(12)
  A(28) = RCT(28)*V(12)*F(12)
  A(29) = RCT(29)*V(11)*F(12)
  A(30) = RCT(30)*V(13)*F(12)
  A(31) = RCT(31)*V(3)*F(15)
  A(32) = RCT(32)*V(2)*F(15)
  A(33) = RCT(33)*V(5)*F(15)
  A(34) = RCT(34)*V(4)*F(15)
  A(35) = RCT(35)*V(7)*F(15)
  A(36) = RCT(36)*V(6)*F(15)
  A(37) = RCT(37)*V(10)*F(15)
  A(38) = RCT(38)*V(9)*F(15)
  A(39) = RCT(39)*V(12)*F(15)
  A(40) = RCT(40)*V(11)*F(15)
  A(41) = RCT(41)*V(14)*F(15)
  A(42) = RCT(42)*V(13)*F(15)
  A(43) = RCT(43)*V(16)*F(14)
  A(44) = RCT(44)*V(3)*F(16)
  A(45) = RCT(45)*V(2)*F(16)
  A(46) = RCT(46)*V(5)*F(16)
  A(47) = RCT(47)*V(4)*F(16)
  A(48) = RCT(48)*V(7)*F(16)
  A(49) = RCT(49)*V(6)*F(16)
  A(50) = RCT(50)*V(16)*F(16)
  A(51) = RCT(51)*V(10)*F(16)
  A(52) = RCT(52)*V(9)*F(16)
  A(53) = RCT(53)*V(12)*F(16)
  A(54) = RCT(54)*V(11)*F(16)
  A(55) = RCT(55)*V(14)*F(16)
  A(56) = RCT(56)*V(13)*F(16)
  A(57) = RCT(57)*V(17)*F(14)

! Aout
  if(present(Aout)) Aout(:) = A(:)

! Aggregate function
  Vdot(1) = A(44)+A(45)+A(46)+A(47)+A(48)+A(49)+A(50)+A(51)+A(52)+A(53)+A(54)+A(55)+A(56)
  Vdot(2) = A(4)-A(11)-A(32)-A(45)
  Vdot(3) = A(5)-A(12)-A(31)-A(44)
  Vdot(4) = A(6)-A(16)-A(34)-A(47)
  Vdot(5) = A(7)-A(15)-A(33)-A(46)
  Vdot(6) = A(8)-A(14)-A(36)-A(49)
  Vdot(7) = A(9)+A(11)+A(12)-A(13)-A(35)-A(48)
  Vdot(8) = A(1)-A(2)-A(3)-A(4)-A(5)-A(6)-A(7)-A(8)-A(9)-A(10)+A(13)+A(14)+A(15)+A(16)
  Vdot(9) = A(19)-A(27)-A(38)-A(52)
  Vdot(10) = A(20)-A(26)-A(37)-A(51)
  Vdot(11) = A(21)-A(29)-A(40)-A(54)
  Vdot(12) = A(22)-A(28)-A(39)-A(53)
  Vdot(13) = A(23)-A(30)-A(42)-A(56)
  Vdot(14) = A(24)-A(25)-A(41)-A(55)
  Vdot(15) = A(17)-A(18)-A(19)-A(20)-A(21)-A(22)-A(23)-A(24)+A(25)+A(26)+A(27)+A(28)+A(29)+A(30)
  Vdot(16) = A(31)+A(32)+A(33)+A(34)+A(35)+A(36)+A(37)+A(38)+A(39)+A(40)+A(41)+A(42)-A(43)-A(50)
  Vdot(17) = A(44)+A(45)+A(46)+A(47)+A(48)+A(49)+A(50)+A(51)+A(52)+A(53)+A(54)+A(55)+A(56)-A(57)
  Vdot(18) = -A(1)+A(2)+A(3)+A(10)-A(17)+A(18)+A(43)+A(57)
      
END SUBROUTINE Fun

! End of Fun function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Function

