! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Sat Jul 25 22:40:36 2020
! Working directory    : /net/seasasfs02/srv/export/seasasfs02/share_root/vshah/Hg/GC_Hg/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(30) :: SPC_NAMES = (/ &
     'HGIICLp        ','HGIIORGp       ','HGBRNO2        ', & ! index 1 - 3
     'HGBRHO2        ','HGBRCLO        ','HGBRBRO        ', & ! index 4 - 6
     'HGBR2          ','HGCLNO2        ','HGCLHO2        ', & ! index 7 - 9
     'HGCLCLO        ','HGCLBRO        ','HGCLBR         ', & ! index 10 - 12
     'HGBRO          ','HGBROH         ','HGBR           ', & ! index 13 - 15
     'Hg0            ','HGCLO          ','HGCL           ', & ! index 16 - 18
     'HGCLOH         ','Br             ','Cl             ', & ! index 19 - 21
     'OH             ','NO2            ','NO             ', & ! index 22 - 24
     'O3             ','HO2            ','BrO            ', & ! index 25 - 27
     'ClO            ','CO             ','CH4            ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '   Hg0 + Br --> HGBR                                                                                ', & ! index 1
     '       HGBR --> Hg0                                                                                 ', & ! index 2
     '  HGBR + Br --> Hg0                                                                                 ', & ! index 3
     ' HGBR + NO2 --> HGBRNO2                                                                             ', & ! index 4
     ' HGBR + HO2 --> HGBRHO2                                                                             ', & ! index 5
     ' HGBR + ClO --> HGBRCLO                                                                             ', & ! index 6
     ' HGBR + BrO --> HGBRBRO                                                                             ', & ! index 7
     '  HGBR + OH --> HGBROH                                                                              ', & ! index 8
     '  HGBR + Br --> HGBR2                                                                               ', & ! index 9
     '  HGBR + O3 --> HGBRO                                                                               ', & ! index 10
     'HGBRO + CH4 --> HGBROH                                                                              ', & ! index 11
     ' HGBRO + CO --> HGBR                                                                                ', & ! index 12
     '   Hg0 + Cl --> HGCL                                                                                ', & ! index 13
     '  HGCL + Cl --> Hg0                                                                                 ', & ! index 14
     ' HGCL + NO2 --> HGCLNO2                                                                             ', & ! index 15
     ' HGCL + HO2 --> HGCLHO2                                                                             ', & ! index 16
     ' HGCL + ClO --> HGCLCLO                                                                             ', & ! index 17
     ' HGCL + BrO --> HGCLBRO                                                                             ', & ! index 18
     '  HGCL + Br --> HGCLBR                                                                              ', & ! index 19
     '  HGCL + OH --> HGCLOH                                                                              ', & ! index 20
     '  HGCL + O3 --> HGCLO                                                                               ', & ! index 21
     'HGCLO + CH4 --> HGCLOH                                                                              ', & ! index 22
     ' HGCLO + CO --> HGCL                                                                                ', & ! index 23
     '    HGBRNO2 --> HGIICLp                                                                             ', & ! index 24
     '    HGBRHO2 --> HGIICLp                                                                             ', & ! index 25
     '     HGBROH --> HGIICLp                                                                             ', & ! index 26
     '    HGBRBRO --> HGIICLp                                                                             ', & ! index 27
     '    HGBRCLO --> HGIICLp                                                                             ', & ! index 28
     '      HGBR2 --> HGIICLp                                                                             ', & ! index 29
     '    HGCLNO2 --> HGIICLp                                                                             ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     '    HGCLHO2 --> HGIICLp                                                                             ', & ! index 31
     '     HGCLOH --> HGIICLp                                                                             ', & ! index 32
     '    HGCLBRO --> HGIICLp                                                                             ', & ! index 33
     '    HGCLCLO --> HGIICLp                                                                             ', & ! index 34
     '     HGCLBR --> HGIICLp                                                                             ', & ! index 35
     '    HGBRNO2 --> HGIIORGp                                                                            ', & ! index 36
     '    HGBRHO2 --> HGIIORGp                                                                            ', & ! index 37
     '     HGBROH --> HGIIORGp                                                                            ', & ! index 38
     '    HGBRBRO --> HGIIORGp                                                                            ', & ! index 39
     '    HGBRCLO --> HGIIORGp                                                                            ', & ! index 40
     '      HGBR2 --> HGIIORGp                                                                            ', & ! index 41
     '    HGCLNO2 --> HGIIORGp                                                                            ', & ! index 42
     '    HGCLHO2 --> HGIIORGp                                                                            ', & ! index 43
     '     HGCLOH --> HGIIORGp                                                                            ', & ! index 44
     '    HGCLBRO --> HGIIORGp                                                                            ', & ! index 45
     '    HGCLCLO --> HGIIORGp                                                                            ', & ! index 46
     '     HGCLBR --> HGIIORGp                                                                            ', & ! index 47
     '        NO2 --> NO + O3                                                                             ', & ! index 48
     '        BrO --> Br + O3                                                                             ', & ! index 49
     '        ClO --> Cl + O3                                                                             ', & ! index 50
     '       HGBR --> Hg0 + Br                                                                            ', & ! index 51
     '    HGBRNO2 --> HGBRO + NO                                                                          ', & ! index 52
     '    HGBRHO2 --> HGBRO + OH                                                                          ', & ! index 53
     '     HGBROH --> HGBR + OH                                                                           ', & ! index 54
     '      HGBR2 --> HGBR + Br                                                                           ', & ! index 55
     '    HGBRBRO --> HGBR + BrO                                                                          ', & ! index 56
     '    HGBRCLO --> HGBR + ClO                                                                          ', & ! index 57
     '       HGCL --> Hg0 + Cl                                                                            ', & ! index 58
     '    HGCLNO2 --> HGCLO + NO                                                                          ', & ! index 59
     '    HGCLHO2 --> HGCLO + OH                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(4) :: EQN_NAMES_2 = (/ &
     '     HGCLOH --> HGCL + OH                                                                           ', & ! index 61
     '     HGCLBR --> HGCL + Br                                                                           ', & ! index 62
     '    HGCLBRO --> HGCL + BrO                                                                          ', & ! index 63
     '    HGCLCLO --> HGCL + ClO                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(64) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2 /)

  CHARACTER(LEN=15), DIMENSION(1) :: FAM_NAMES
! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
