! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Jacobian.f90
! Time                 : Sat Jul 25 22:40:36 2020
! Working directory    : /net/seasasfs02/srv/export/seasasfs02/share_root/vshah/Hg/GC_Hg/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Jacobian

  USE gckpp_Parameters
  USE gckpp_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(86)

! B(1) = dA(1)/dV(16)
  B(1) = RCT(1)*F(1)
! B(3) = dA(2)/dV(15)
  B(3) = RCT(2)
! B(4) = dA(3)/dV(15)
  B(4) = RCT(3)*F(1)
! B(6) = dA(4)/dV(15)
  B(6) = RCT(4)*F(4)
! B(8) = dA(5)/dV(15)
  B(8) = RCT(5)*F(7)
! B(10) = dA(6)/dV(15)
  B(10) = RCT(6)*F(9)
! B(12) = dA(7)/dV(15)
  B(12) = RCT(7)*F(8)
! B(14) = dA(8)/dV(15)
  B(14) = RCT(8)*F(3)
! B(16) = dA(9)/dV(15)
  B(16) = RCT(9)*F(1)
! B(18) = dA(10)/dV(15)
  B(18) = RCT(10)*F(6)
! B(20) = dA(11)/dV(13)
  B(20) = RCT(11)*F(11)
! B(22) = dA(12)/dV(13)
  B(22) = RCT(12)*F(10)
! B(24) = dA(13)/dV(16)
  B(24) = RCT(13)*F(2)
! B(26) = dA(14)/dV(18)
  B(26) = RCT(14)*F(2)
! B(28) = dA(15)/dV(18)
  B(28) = RCT(15)*F(4)
! B(30) = dA(16)/dV(18)
  B(30) = RCT(16)*F(7)
! B(32) = dA(17)/dV(18)
  B(32) = RCT(17)*F(9)
! B(34) = dA(18)/dV(18)
  B(34) = RCT(18)*F(8)
! B(36) = dA(19)/dV(18)
  B(36) = RCT(19)*F(1)
! B(38) = dA(20)/dV(18)
  B(38) = RCT(20)*F(3)
! B(40) = dA(21)/dV(18)
  B(40) = RCT(21)*F(6)
! B(42) = dA(22)/dV(17)
  B(42) = RCT(22)*F(11)
! B(44) = dA(23)/dV(17)
  B(44) = RCT(23)*F(10)
! B(46) = dA(24)/dV(3)
  B(46) = RCT(24)
! B(47) = dA(25)/dV(4)
  B(47) = RCT(25)
! B(48) = dA(26)/dV(14)
  B(48) = RCT(26)
! B(49) = dA(27)/dV(6)
  B(49) = RCT(27)
! B(50) = dA(28)/dV(5)
  B(50) = RCT(28)
! B(51) = dA(29)/dV(7)
  B(51) = RCT(29)
! B(52) = dA(30)/dV(8)
  B(52) = RCT(30)
! B(53) = dA(31)/dV(9)
  B(53) = RCT(31)
! B(54) = dA(32)/dV(19)
  B(54) = RCT(32)
! B(55) = dA(33)/dV(11)
  B(55) = RCT(33)
! B(56) = dA(34)/dV(10)
  B(56) = RCT(34)
! B(57) = dA(35)/dV(12)
  B(57) = RCT(35)
! B(58) = dA(36)/dV(3)
  B(58) = RCT(36)
! B(59) = dA(37)/dV(4)
  B(59) = RCT(37)
! B(60) = dA(38)/dV(14)
  B(60) = RCT(38)
! B(61) = dA(39)/dV(6)
  B(61) = RCT(39)
! B(62) = dA(40)/dV(5)
  B(62) = RCT(40)
! B(63) = dA(41)/dV(7)
  B(63) = RCT(41)
! B(64) = dA(42)/dV(8)
  B(64) = RCT(42)
! B(65) = dA(43)/dV(9)
  B(65) = RCT(43)
! B(66) = dA(44)/dV(19)
  B(66) = RCT(44)
! B(67) = dA(45)/dV(11)
  B(67) = RCT(45)
! B(68) = dA(46)/dV(10)
  B(68) = RCT(46)
! B(69) = dA(47)/dV(12)
  B(69) = RCT(47)
! B(73) = dA(51)/dV(15)
  B(73) = RCT(51)
! B(74) = dA(52)/dV(3)
  B(74) = RCT(52)
! B(75) = dA(53)/dV(4)
  B(75) = RCT(53)
! B(76) = dA(54)/dV(14)
  B(76) = RCT(54)
! B(77) = dA(55)/dV(7)
  B(77) = RCT(55)
! B(78) = dA(56)/dV(6)
  B(78) = RCT(56)
! B(79) = dA(57)/dV(5)
  B(79) = RCT(57)
! B(80) = dA(58)/dV(18)
  B(80) = RCT(58)
! B(81) = dA(59)/dV(8)
  B(81) = RCT(59)
! B(82) = dA(60)/dV(9)
  B(82) = RCT(60)
! B(83) = dA(61)/dV(19)
  B(83) = RCT(61)
! B(84) = dA(62)/dV(12)
  B(84) = RCT(62)
! B(85) = dA(63)/dV(11)
  B(85) = RCT(63)
! B(86) = dA(64)/dV(10)
  B(86) = RCT(64)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,3)
  JVS(2) = B(46)
! JVS(3) = Jac_FULL(1,4)
  JVS(3) = B(47)
! JVS(4) = Jac_FULL(1,5)
  JVS(4) = B(50)
! JVS(5) = Jac_FULL(1,6)
  JVS(5) = B(49)
! JVS(6) = Jac_FULL(1,7)
  JVS(6) = B(51)
! JVS(7) = Jac_FULL(1,8)
  JVS(7) = B(52)
! JVS(8) = Jac_FULL(1,9)
  JVS(8) = B(53)
! JVS(9) = Jac_FULL(1,10)
  JVS(9) = B(56)
! JVS(10) = Jac_FULL(1,11)
  JVS(10) = B(55)
! JVS(11) = Jac_FULL(1,12)
  JVS(11) = B(57)
! JVS(12) = Jac_FULL(1,14)
  JVS(12) = B(48)
! JVS(13) = Jac_FULL(1,19)
  JVS(13) = B(54)
! JVS(14) = Jac_FULL(2,2)
  JVS(14) = 0
! JVS(15) = Jac_FULL(2,3)
  JVS(15) = B(58)
! JVS(16) = Jac_FULL(2,4)
  JVS(16) = B(59)
! JVS(17) = Jac_FULL(2,5)
  JVS(17) = B(62)
! JVS(18) = Jac_FULL(2,6)
  JVS(18) = B(61)
! JVS(19) = Jac_FULL(2,7)
  JVS(19) = B(63)
! JVS(20) = Jac_FULL(2,8)
  JVS(20) = B(64)
! JVS(21) = Jac_FULL(2,9)
  JVS(21) = B(65)
! JVS(22) = Jac_FULL(2,10)
  JVS(22) = B(68)
! JVS(23) = Jac_FULL(2,11)
  JVS(23) = B(67)
! JVS(24) = Jac_FULL(2,12)
  JVS(24) = B(69)
! JVS(25) = Jac_FULL(2,14)
  JVS(25) = B(60)
! JVS(26) = Jac_FULL(2,19)
  JVS(26) = B(66)
! JVS(27) = Jac_FULL(3,3)
  JVS(27) = -B(46)-B(58)-B(74)
! JVS(28) = Jac_FULL(3,15)
  JVS(28) = B(6)
! JVS(29) = Jac_FULL(4,4)
  JVS(29) = -B(47)-B(59)-B(75)
! JVS(30) = Jac_FULL(4,15)
  JVS(30) = B(8)
! JVS(31) = Jac_FULL(5,5)
  JVS(31) = -B(50)-B(62)-B(79)
! JVS(32) = Jac_FULL(5,15)
  JVS(32) = B(10)
! JVS(33) = Jac_FULL(6,6)
  JVS(33) = -B(49)-B(61)-B(78)
! JVS(34) = Jac_FULL(6,15)
  JVS(34) = B(12)
! JVS(35) = Jac_FULL(7,7)
  JVS(35) = -B(51)-B(63)-B(77)
! JVS(36) = Jac_FULL(7,15)
  JVS(36) = B(16)
! JVS(37) = Jac_FULL(8,8)
  JVS(37) = -B(52)-B(64)-B(81)
! JVS(38) = Jac_FULL(8,18)
  JVS(38) = B(28)
! JVS(39) = Jac_FULL(9,9)
  JVS(39) = -B(53)-B(65)-B(82)
! JVS(40) = Jac_FULL(9,18)
  JVS(40) = B(30)
! JVS(41) = Jac_FULL(10,10)
  JVS(41) = -B(56)-B(68)-B(86)
! JVS(42) = Jac_FULL(10,18)
  JVS(42) = B(32)
! JVS(43) = Jac_FULL(11,11)
  JVS(43) = -B(55)-B(67)-B(85)
! JVS(44) = Jac_FULL(11,18)
  JVS(44) = B(34)
! JVS(45) = Jac_FULL(12,12)
  JVS(45) = -B(57)-B(69)-B(84)
! JVS(46) = Jac_FULL(12,18)
  JVS(46) = B(36)
! JVS(47) = Jac_FULL(13,3)
  JVS(47) = B(74)
! JVS(48) = Jac_FULL(13,4)
  JVS(48) = B(75)
! JVS(49) = Jac_FULL(13,13)
  JVS(49) = -B(20)-B(22)
! JVS(50) = Jac_FULL(13,15)
  JVS(50) = B(18)
! JVS(51) = Jac_FULL(14,13)
  JVS(51) = B(20)
! JVS(52) = Jac_FULL(14,14)
  JVS(52) = -B(48)-B(60)-B(76)
! JVS(53) = Jac_FULL(14,15)
  JVS(53) = B(14)
! JVS(54) = Jac_FULL(15,5)
  JVS(54) = B(79)
! JVS(55) = Jac_FULL(15,6)
  JVS(55) = B(78)
! JVS(56) = Jac_FULL(15,7)
  JVS(56) = B(77)
! JVS(57) = Jac_FULL(15,13)
  JVS(57) = B(22)
! JVS(58) = Jac_FULL(15,14)
  JVS(58) = B(76)
! JVS(59) = Jac_FULL(15,15)
  JVS(59) = -B(3)-B(4)-B(6)-B(8)-B(10)-B(12)-B(14)-B(16)-B(18)-B(73)
! JVS(60) = Jac_FULL(15,16)
  JVS(60) = B(1)
! JVS(61) = Jac_FULL(16,15)
  JVS(61) = B(3)+B(4)+B(73)
! JVS(62) = Jac_FULL(16,16)
  JVS(62) = -B(1)-B(24)
! JVS(63) = Jac_FULL(16,18)
  JVS(63) = B(26)+B(80)
! JVS(64) = Jac_FULL(17,8)
  JVS(64) = B(81)
! JVS(65) = Jac_FULL(17,9)
  JVS(65) = B(82)
! JVS(66) = Jac_FULL(17,17)
  JVS(66) = -B(42)-B(44)
! JVS(67) = Jac_FULL(17,18)
  JVS(67) = B(40)
! JVS(68) = Jac_FULL(18,10)
  JVS(68) = B(86)
! JVS(69) = Jac_FULL(18,11)
  JVS(69) = B(85)
! JVS(70) = Jac_FULL(18,12)
  JVS(70) = B(84)
! JVS(71) = Jac_FULL(18,16)
  JVS(71) = B(24)
! JVS(72) = Jac_FULL(18,17)
  JVS(72) = B(44)
! JVS(73) = Jac_FULL(18,18)
  JVS(73) = -B(26)-B(28)-B(30)-B(32)-B(34)-B(36)-B(38)-B(40)-B(80)
! JVS(74) = Jac_FULL(18,19)
  JVS(74) = B(83)
! JVS(75) = Jac_FULL(19,17)
  JVS(75) = B(42)
! JVS(76) = Jac_FULL(19,18)
  JVS(76) = B(38)
! JVS(77) = Jac_FULL(19,19)
  JVS(77) = -B(54)-B(66)-B(83)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(3)+JVS(3)*UV(4)+JVS(4)*UV(5)+JVS(5)*UV(6)+JVS(6)*UV(7)+JVS(7)*UV(8)+JVS(8)*UV(9)&
             &+JVS(9)*UV(10)+JVS(10)*UV(11)+JVS(11)*UV(12)+JVS(12)*UV(14)+JVS(13)*UV(19)
  JUV(2) = JVS(14)*UV(2)+JVS(15)*UV(3)+JVS(16)*UV(4)+JVS(17)*UV(5)+JVS(18)*UV(6)+JVS(19)*UV(7)+JVS(20)*UV(8)+JVS(21)&
             &*UV(9)+JVS(22)*UV(10)+JVS(23)*UV(11)+JVS(24)*UV(12)+JVS(25)*UV(14)+JVS(26)*UV(19)
  JUV(3) = JVS(27)*UV(3)+JVS(28)*UV(15)
  JUV(4) = JVS(29)*UV(4)+JVS(30)*UV(15)
  JUV(5) = JVS(31)*UV(5)+JVS(32)*UV(15)
  JUV(6) = JVS(33)*UV(6)+JVS(34)*UV(15)
  JUV(7) = JVS(35)*UV(7)+JVS(36)*UV(15)
  JUV(8) = JVS(37)*UV(8)+JVS(38)*UV(18)
  JUV(9) = JVS(39)*UV(9)+JVS(40)*UV(18)
  JUV(10) = JVS(41)*UV(10)+JVS(42)*UV(18)
  JUV(11) = JVS(43)*UV(11)+JVS(44)*UV(18)
  JUV(12) = JVS(45)*UV(12)+JVS(46)*UV(18)
  JUV(13) = JVS(47)*UV(3)+JVS(48)*UV(4)+JVS(49)*UV(13)+JVS(50)*UV(15)
  JUV(14) = JVS(51)*UV(13)+JVS(52)*UV(14)+JVS(53)*UV(15)
  JUV(15) = JVS(54)*UV(5)+JVS(55)*UV(6)+JVS(56)*UV(7)+JVS(57)*UV(13)+JVS(58)*UV(14)+JVS(59)*UV(15)+JVS(60)*UV(16)
  JUV(16) = JVS(61)*UV(15)+JVS(62)*UV(16)+JVS(63)*UV(18)
  JUV(17) = JVS(64)*UV(8)+JVS(65)*UV(9)+JVS(66)*UV(17)+JVS(67)*UV(18)
  JUV(18) = JVS(68)*UV(10)+JVS(69)*UV(11)+JVS(70)*UV(12)+JVS(71)*UV(16)+JVS(72)*UV(17)+JVS(73)*UV(18)+JVS(74)*UV(19)
  JUV(19) = JVS(75)*UV(17)+JVS(76)*UV(18)+JVS(77)*UV(19)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(14)*UV(2)
  JTUV(3) = JVS(2)*UV(1)+JVS(15)*UV(2)+JVS(27)*UV(3)+JVS(47)*UV(13)
  JTUV(4) = JVS(3)*UV(1)+JVS(16)*UV(2)+JVS(29)*UV(4)+JVS(48)*UV(13)
  JTUV(5) = JVS(4)*UV(1)+JVS(17)*UV(2)+JVS(31)*UV(5)+JVS(54)*UV(15)
  JTUV(6) = JVS(5)*UV(1)+JVS(18)*UV(2)+JVS(33)*UV(6)+JVS(55)*UV(15)
  JTUV(7) = JVS(6)*UV(1)+JVS(19)*UV(2)+JVS(35)*UV(7)+JVS(56)*UV(15)
  JTUV(8) = JVS(7)*UV(1)+JVS(20)*UV(2)+JVS(37)*UV(8)+JVS(64)*UV(17)
  JTUV(9) = JVS(8)*UV(1)+JVS(21)*UV(2)+JVS(39)*UV(9)+JVS(65)*UV(17)
  JTUV(10) = JVS(9)*UV(1)+JVS(22)*UV(2)+JVS(41)*UV(10)+JVS(68)*UV(18)
  JTUV(11) = JVS(10)*UV(1)+JVS(23)*UV(2)+JVS(43)*UV(11)+JVS(69)*UV(18)
  JTUV(12) = JVS(11)*UV(1)+JVS(24)*UV(2)+JVS(45)*UV(12)+JVS(70)*UV(18)
  JTUV(13) = JVS(49)*UV(13)+JVS(51)*UV(14)+JVS(57)*UV(15)
  JTUV(14) = JVS(12)*UV(1)+JVS(25)*UV(2)+JVS(52)*UV(14)+JVS(58)*UV(15)
  JTUV(15) = JVS(28)*UV(3)+JVS(30)*UV(4)+JVS(32)*UV(5)+JVS(34)*UV(6)+JVS(36)*UV(7)+JVS(50)*UV(13)+JVS(53)*UV(14)+JVS(59)&
               &*UV(15)+JVS(61)*UV(16)
  JTUV(16) = JVS(60)*UV(15)+JVS(62)*UV(16)+JVS(71)*UV(18)
  JTUV(17) = JVS(66)*UV(17)+JVS(72)*UV(18)+JVS(75)*UV(19)
  JTUV(18) = JVS(38)*UV(8)+JVS(40)*UV(9)+JVS(42)*UV(10)+JVS(44)*UV(11)+JVS(46)*UV(12)+JVS(63)*UV(16)+JVS(67)*UV(17)&
               &+JVS(73)*UV(18)+JVS(76)*UV(19)
  JTUV(19) = JVS(13)*UV(1)+JVS(26)*UV(2)+JVS(74)*UV(18)+JVS(77)*UV(19)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Jacobian

