! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Sat Jun 13 16:28:15 2020
! Working directory    : /n/home02/thackray/GC_working/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(6) :: SPC_NAMES = (/ &
     'Hg0            ','Hg2            ','HgP            ', & ! index 1 - 3
     'NO2            ','PHg            ','OH             ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(4) :: EQN_NAMES = (/ &
     '     Hg0 --> HgP + PHg                                                                              ', & ! index 1
     '     Hg0 --> Hg2                                                                                    ', & ! index 2
     'Hg2 + OH --> NO2                                                                                    ', & ! index 3
     '     Hg2 --> NO2                                                                                    ' /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(1) :: FAM_NAMES = (/ &
     'PHg            ' /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
