! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! The ODE Jacobian of Chemical Model File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Jacobian.f90
! Time                 : Mon Jun 29 11:32:40 2020
! Working directory    : /n/home02/thackray/GC_working/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Jacobian

  USE gckpp_Parameters
  USE gckpp_JacobianSP

  IMPLICIT NONE

CONTAINS


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP - the Jacobian of Variables in sparse matrix representation
!   Arguments :
!      V         - Concentrations of variable species (local)
!      F         - Concentrations of fixed species (local)
!      RCT       - Rate constants (local)
!      JVS       - sparse Jacobian of variables
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP ( V, F, RCT, JVS )

! V - Concentrations of variable species (local)
  REAL(kind=dp) :: V(NVAR)
! F - Concentrations of fixed species (local)
  REAL(kind=dp) :: F(NFIX)
! RCT - Rate constants (local)
  REAL(kind=dp) :: RCT(NREACT)
! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)


! Local variables
! B - Temporary array
  REAL(kind=dp) :: B(102)

! B(1) = dA(1)/dV(18)
  B(1) = RCT(1)*F(11)
! B(3) = dA(2)/dV(18)
  B(3) = RCT(2)*F(12)
! B(5) = dA(3)/dV(18)
  B(5) = RCT(3)*F(13)
! B(7) = dA(4)/dV(18)
  B(7) = RCT(4)*F(14)
! B(9) = dA(5)/dV(18)
  B(9) = RCT(5)*F(15)
! B(11) = dA(6)/dV(18)
  B(11) = RCT(6)*F(16)
! B(13) = dA(7)/dV(18)
  B(13) = RCT(7)*F(17)
! B(15) = dA(8)/dV(18)
  B(15) = RCT(8)*F(18)
! B(17) = dA(9)/dV(18)
  B(17) = RCT(9)*F(19)
! B(19) = dA(10)/dV(18)
  B(19) = RCT(10)*F(20)
! B(21) = dA(11)/dV(18)
  B(21) = RCT(11)*F(1)
! B(23) = dA(12)/dV(8)
  B(23) = RCT(12)
! B(24) = dA(13)/dV(8)
  B(24) = RCT(13)*F(1)
! B(26) = dA(14)/dV(8)
  B(26) = RCT(14)*F(4)
! B(28) = dA(15)/dV(8)
  B(28) = RCT(15)*F(5)
! B(30) = dA(16)/dV(8)
  B(30) = RCT(16)*F(7)
! B(32) = dA(17)/dV(8)
  B(32) = RCT(17)*F(6)
! B(34) = dA(18)/dV(8)
  B(34) = RCT(18)*F(1)
! B(36) = dA(19)/dV(8)
  B(36) = RCT(19)*F(3)
! B(38) = dA(20)/dV(8)
  B(38) = RCT(20)*F(9)
! B(40) = dA(21)/dV(18)
  B(40) = RCT(21)*F(2)
! B(42) = dA(22)/dV(15)
  B(42) = RCT(22)*F(2)
! B(44) = dA(23)/dV(15)
  B(44) = RCT(23)*F(4)
! B(46) = dA(24)/dV(15)
  B(46) = RCT(24)*F(5)
! B(48) = dA(25)/dV(15)
  B(48) = RCT(25)*F(7)
! B(50) = dA(26)/dV(15)
  B(50) = RCT(26)*F(6)
! B(52) = dA(27)/dV(15)
  B(52) = RCT(27)*F(1)
! B(54) = dA(28)/dV(15)
  B(54) = RCT(28)*F(3)
! B(56) = dA(29)/dV(14)
  B(56) = RCT(29)*F(8)
! B(58) = dA(30)/dV(10)
  B(58) = RCT(30)*F(8)
! B(60) = dA(31)/dV(9)
  B(60) = RCT(31)*F(8)
! B(62) = dA(32)/dV(12)
  B(62) = RCT(32)*F(8)
! B(64) = dA(33)/dV(11)
  B(64) = RCT(33)*F(8)
! B(66) = dA(34)/dV(13)
  B(66) = RCT(34)*F(8)
! B(68) = dA(35)/dV(16)
  B(68) = RCT(35)*F(10)
! B(70) = dA(36)/dV(17)
  B(70) = RCT(36)*F(10)
! B(72) = dA(37)/dV(3)
  B(72) = RCT(37)
! B(73) = dA(38)/dV(2)
  B(73) = RCT(38)
! B(74) = dA(39)/dV(5)
  B(74) = RCT(39)
! B(75) = dA(40)/dV(4)
  B(75) = RCT(40)
! B(76) = dA(41)/dV(7)
  B(76) = RCT(41)
! B(77) = dA(42)/dV(6)
  B(77) = RCT(42)
! B(78) = dA(43)/dV(16)
  B(78) = RCT(43)
! B(79) = dA(44)/dV(10)
  B(79) = RCT(44)
! B(80) = dA(45)/dV(9)
  B(80) = RCT(45)
! B(81) = dA(46)/dV(12)
  B(81) = RCT(46)
! B(82) = dA(47)/dV(11)
  B(82) = RCT(47)
! B(83) = dA(48)/dV(14)
  B(83) = RCT(48)
! B(84) = dA(49)/dV(13)
  B(84) = RCT(49)
! B(85) = dA(50)/dV(3)
  B(85) = RCT(50)
! B(86) = dA(51)/dV(2)
  B(86) = RCT(51)
! B(87) = dA(52)/dV(5)
  B(87) = RCT(52)
! B(88) = dA(53)/dV(4)
  B(88) = RCT(53)
! B(89) = dA(54)/dV(7)
  B(89) = RCT(54)
! B(90) = dA(55)/dV(6)
  B(90) = RCT(55)
! B(91) = dA(56)/dV(10)
  B(91) = RCT(56)
! B(92) = dA(57)/dV(9)
  B(92) = RCT(57)
! B(93) = dA(58)/dV(12)
  B(93) = RCT(58)
! B(94) = dA(59)/dV(11)
  B(94) = RCT(59)
! B(95) = dA(60)/dV(14)
  B(95) = RCT(60)
! B(96) = dA(61)/dV(13)
  B(96) = RCT(61)
! B(97) = dA(62)/dV(3)
  B(97) = RCT(62)
! B(98) = dA(63)/dV(2)
  B(98) = RCT(63)
! B(99) = dA(64)/dV(7)
  B(99) = RCT(64)
! B(100) = dA(65)/dV(4)
  B(100) = RCT(65)
! B(101) = dA(66)/dV(5)
  B(101) = RCT(66)
! B(102) = dA(67)/dV(6)
  B(102) = RCT(67)

! Construct the Jacobian terms from B's
! JVS(1) = Jac_FULL(1,1)
  JVS(1) = 0
! JVS(2) = Jac_FULL(1,2)
  JVS(2) = B(73)
! JVS(3) = Jac_FULL(1,3)
  JVS(3) = B(72)
! JVS(4) = Jac_FULL(1,4)
  JVS(4) = B(75)
! JVS(5) = Jac_FULL(1,5)
  JVS(5) = B(74)
! JVS(6) = Jac_FULL(1,6)
  JVS(6) = B(77)
! JVS(7) = Jac_FULL(1,7)
  JVS(7) = B(76)
! JVS(8) = Jac_FULL(1,9)
  JVS(8) = B(80)
! JVS(9) = Jac_FULL(1,10)
  JVS(9) = B(79)
! JVS(10) = Jac_FULL(1,11)
  JVS(10) = B(82)
! JVS(11) = Jac_FULL(1,12)
  JVS(11) = B(81)
! JVS(12) = Jac_FULL(1,13)
  JVS(12) = B(84)
! JVS(13) = Jac_FULL(1,14)
  JVS(13) = B(83)
! JVS(14) = Jac_FULL(1,16)
  JVS(14) = B(78)
! JVS(15) = Jac_FULL(2,2)
  JVS(15) = -B(73)-B(86)-B(98)
! JVS(16) = Jac_FULL(2,8)
  JVS(16) = B(26)
! JVS(17) = Jac_FULL(3,3)
  JVS(17) = -B(72)-B(85)-B(97)
! JVS(18) = Jac_FULL(3,8)
  JVS(18) = B(28)
! JVS(19) = Jac_FULL(4,4)
  JVS(19) = -B(75)-B(88)-B(100)
! JVS(20) = Jac_FULL(4,8)
  JVS(20) = B(30)
! JVS(21) = Jac_FULL(5,5)
  JVS(21) = -B(74)-B(87)-B(101)
! JVS(22) = Jac_FULL(5,8)
  JVS(22) = B(32)
! JVS(23) = Jac_FULL(6,6)
  JVS(23) = -B(77)-B(90)-B(102)
! JVS(24) = Jac_FULL(6,8)
  JVS(24) = B(34)
! JVS(25) = Jac_FULL(7,7)
  JVS(25) = -B(76)-B(89)-B(99)
! JVS(26) = Jac_FULL(7,8)
  JVS(26) = B(36)
! JVS(27) = Jac_FULL(8,2)
  JVS(27) = B(98)
! JVS(28) = Jac_FULL(8,3)
  JVS(28) = B(97)
! JVS(29) = Jac_FULL(8,4)
  JVS(29) = B(100)
! JVS(30) = Jac_FULL(8,5)
  JVS(30) = B(101)
! JVS(31) = Jac_FULL(8,6)
  JVS(31) = B(102)
! JVS(32) = Jac_FULL(8,7)
  JVS(32) = B(99)
! JVS(33) = Jac_FULL(8,8)
  JVS(33) = -B(23)-B(24)-B(26)-B(28)-B(30)-B(32)-B(34)-B(36)-B(38)
! JVS(34) = Jac_FULL(8,18)
  JVS(34) = B(1)+B(3)+B(5)+B(7)+B(9)+B(11)+B(13)+B(15)+B(17)+B(19)+B(21)
! JVS(35) = Jac_FULL(9,9)
  JVS(35) = -B(60)-B(80)-B(92)
! JVS(36) = Jac_FULL(9,15)
  JVS(36) = B(44)
! JVS(37) = Jac_FULL(10,10)
  JVS(37) = -B(58)-B(79)-B(91)
! JVS(38) = Jac_FULL(10,15)
  JVS(38) = B(46)
! JVS(39) = Jac_FULL(11,11)
  JVS(39) = -B(64)-B(82)-B(94)
! JVS(40) = Jac_FULL(11,15)
  JVS(40) = B(48)
! JVS(41) = Jac_FULL(12,12)
  JVS(41) = -B(62)-B(81)-B(93)
! JVS(42) = Jac_FULL(12,15)
  JVS(42) = B(50)
! JVS(43) = Jac_FULL(13,13)
  JVS(43) = -B(66)-B(84)-B(96)
! JVS(44) = Jac_FULL(13,15)
  JVS(44) = B(52)
! JVS(45) = Jac_FULL(14,14)
  JVS(45) = -B(56)-B(83)-B(95)
! JVS(46) = Jac_FULL(14,15)
  JVS(46) = B(54)
! JVS(47) = Jac_FULL(15,9)
  JVS(47) = B(60)
! JVS(48) = Jac_FULL(15,10)
  JVS(48) = B(58)
! JVS(49) = Jac_FULL(15,11)
  JVS(49) = B(64)
! JVS(50) = Jac_FULL(15,12)
  JVS(50) = B(62)
! JVS(51) = Jac_FULL(15,13)
  JVS(51) = B(66)
! JVS(52) = Jac_FULL(15,14)
  JVS(52) = B(56)
! JVS(53) = Jac_FULL(15,15)
  JVS(53) = -B(42)-B(44)-B(46)-B(48)-B(50)-B(52)-B(54)
! JVS(54) = Jac_FULL(15,18)
  JVS(54) = B(40)
! JVS(55) = Jac_FULL(16,2)
  JVS(55) = B(86)
! JVS(56) = Jac_FULL(16,3)
  JVS(56) = B(85)
! JVS(57) = Jac_FULL(16,4)
  JVS(57) = B(88)
! JVS(58) = Jac_FULL(16,5)
  JVS(58) = B(87)
! JVS(59) = Jac_FULL(16,6)
  JVS(59) = B(90)
! JVS(60) = Jac_FULL(16,7)
  JVS(60) = B(89)
! JVS(61) = Jac_FULL(16,8)
  JVS(61) = 0
! JVS(62) = Jac_FULL(16,9)
  JVS(62) = B(92)
! JVS(63) = Jac_FULL(16,10)
  JVS(63) = B(91)
! JVS(64) = Jac_FULL(16,11)
  JVS(64) = B(94)
! JVS(65) = Jac_FULL(16,12)
  JVS(65) = B(93)
! JVS(66) = Jac_FULL(16,13)
  JVS(66) = B(96)
! JVS(67) = Jac_FULL(16,14)
  JVS(67) = B(95)
! JVS(68) = Jac_FULL(16,15)
  JVS(68) = 0
! JVS(69) = Jac_FULL(16,16)
  JVS(69) = -B(68)-B(78)
! JVS(70) = Jac_FULL(16,18)
  JVS(70) = 0
! JVS(71) = Jac_FULL(17,2)
  JVS(71) = B(73)
! JVS(72) = Jac_FULL(17,3)
  JVS(72) = B(72)
! JVS(73) = Jac_FULL(17,4)
  JVS(73) = B(75)
! JVS(74) = Jac_FULL(17,5)
  JVS(74) = B(74)
! JVS(75) = Jac_FULL(17,6)
  JVS(75) = B(77)
! JVS(76) = Jac_FULL(17,7)
  JVS(76) = B(76)
! JVS(77) = Jac_FULL(17,8)
  JVS(77) = 0
! JVS(78) = Jac_FULL(17,9)
  JVS(78) = B(80)
! JVS(79) = Jac_FULL(17,10)
  JVS(79) = B(79)
! JVS(80) = Jac_FULL(17,11)
  JVS(80) = B(82)
! JVS(81) = Jac_FULL(17,12)
  JVS(81) = B(81)
! JVS(82) = Jac_FULL(17,13)
  JVS(82) = B(84)
! JVS(83) = Jac_FULL(17,14)
  JVS(83) = B(83)
! JVS(84) = Jac_FULL(17,15)
  JVS(84) = 0
! JVS(85) = Jac_FULL(17,16)
  JVS(85) = B(78)
! JVS(86) = Jac_FULL(17,17)
  JVS(86) = -B(70)
! JVS(87) = Jac_FULL(17,18)
  JVS(87) = 0
! JVS(88) = Jac_FULL(18,8)
  JVS(88) = B(23)+B(24)+B(38)
! JVS(89) = Jac_FULL(18,15)
  JVS(89) = B(42)
! JVS(90) = Jac_FULL(18,16)
  JVS(90) = B(68)
! JVS(91) = Jac_FULL(18,17)
  JVS(91) = B(70)
! JVS(92) = Jac_FULL(18,18)
  JVS(92) = -B(1)-B(3)-B(5)-B(7)-B(9)-B(11)-B(13)-B(15)-B(17)-B(19)-B(21)-B(40)
      
END SUBROUTINE Jac_SP

! End of Jac_SP function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Jac_SP_Vec - function for sparse multiplication: sparse Jacobian times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JUV       - Jacobian times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE Jac_SP_Vec ( JVS, UV, JUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JUV - Jacobian times user vector
  REAL(kind=dp) :: JUV(NVAR)

  JUV(1) = JVS(1)*UV(1)+JVS(2)*UV(2)+JVS(3)*UV(3)+JVS(4)*UV(4)+JVS(5)*UV(5)+JVS(6)*UV(6)+JVS(7)*UV(7)+JVS(8)*UV(9)&
             &+JVS(9)*UV(10)+JVS(10)*UV(11)+JVS(11)*UV(12)+JVS(12)*UV(13)+JVS(13)*UV(14)+JVS(14)*UV(16)
  JUV(2) = JVS(15)*UV(2)+JVS(16)*UV(8)
  JUV(3) = JVS(17)*UV(3)+JVS(18)*UV(8)
  JUV(4) = JVS(19)*UV(4)+JVS(20)*UV(8)
  JUV(5) = JVS(21)*UV(5)+JVS(22)*UV(8)
  JUV(6) = JVS(23)*UV(6)+JVS(24)*UV(8)
  JUV(7) = JVS(25)*UV(7)+JVS(26)*UV(8)
  JUV(8) = JVS(27)*UV(2)+JVS(28)*UV(3)+JVS(29)*UV(4)+JVS(30)*UV(5)+JVS(31)*UV(6)+JVS(32)*UV(7)+JVS(33)*UV(8)+JVS(34)&
             &*UV(18)
  JUV(9) = JVS(35)*UV(9)+JVS(36)*UV(15)
  JUV(10) = JVS(37)*UV(10)+JVS(38)*UV(15)
  JUV(11) = JVS(39)*UV(11)+JVS(40)*UV(15)
  JUV(12) = JVS(41)*UV(12)+JVS(42)*UV(15)
  JUV(13) = JVS(43)*UV(13)+JVS(44)*UV(15)
  JUV(14) = JVS(45)*UV(14)+JVS(46)*UV(15)
  JUV(15) = JVS(47)*UV(9)+JVS(48)*UV(10)+JVS(49)*UV(11)+JVS(50)*UV(12)+JVS(51)*UV(13)+JVS(52)*UV(14)+JVS(53)*UV(15)&
              &+JVS(54)*UV(18)
  JUV(16) = JVS(55)*UV(2)+JVS(56)*UV(3)+JVS(57)*UV(4)+JVS(58)*UV(5)+JVS(59)*UV(6)+JVS(60)*UV(7)+JVS(62)*UV(9)+JVS(63)&
              &*UV(10)+JVS(64)*UV(11)+JVS(65)*UV(12)+JVS(66)*UV(13)+JVS(67)*UV(14)+JVS(69)*UV(16)
  JUV(17) = JVS(71)*UV(2)+JVS(72)*UV(3)+JVS(73)*UV(4)+JVS(74)*UV(5)+JVS(75)*UV(6)+JVS(76)*UV(7)+JVS(78)*UV(9)+JVS(79)&
              &*UV(10)+JVS(80)*UV(11)+JVS(81)*UV(12)+JVS(82)*UV(13)+JVS(83)*UV(14)+JVS(85)*UV(16)+JVS(86)*UV(17)
  JUV(18) = JVS(88)*UV(8)+JVS(89)*UV(15)+JVS(90)*UV(16)+JVS(91)*UV(17)+JVS(92)*UV(18)
      
END SUBROUTINE Jac_SP_Vec

! End of Jac_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! JacTR_SP_Vec - sparse multiplication: sparse Jacobian transposed times vector
!   Arguments :
!      JVS       - sparse Jacobian of variables
!      UV        - User vector for variables
!      JTUV      - Jacobian transposed times user vector
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

SUBROUTINE JacTR_SP_Vec ( JVS, UV, JTUV )

! JVS - sparse Jacobian of variables
  REAL(kind=dp) :: JVS(LU_NONZERO)
! UV - User vector for variables
  REAL(kind=dp) :: UV(NVAR)
! JTUV - Jacobian transposed times user vector
  REAL(kind=dp) :: JTUV(NVAR)

  JTUV(1) = JVS(1)*UV(1)
  JTUV(2) = JVS(2)*UV(1)+JVS(15)*UV(2)+JVS(27)*UV(8)+JVS(55)*UV(16)+JVS(71)*UV(17)
  JTUV(3) = JVS(3)*UV(1)+JVS(17)*UV(3)+JVS(28)*UV(8)+JVS(56)*UV(16)+JVS(72)*UV(17)
  JTUV(4) = JVS(4)*UV(1)+JVS(19)*UV(4)+JVS(29)*UV(8)+JVS(57)*UV(16)+JVS(73)*UV(17)
  JTUV(5) = JVS(5)*UV(1)+JVS(21)*UV(5)+JVS(30)*UV(8)+JVS(58)*UV(16)+JVS(74)*UV(17)
  JTUV(6) = JVS(6)*UV(1)+JVS(23)*UV(6)+JVS(31)*UV(8)+JVS(59)*UV(16)+JVS(75)*UV(17)
  JTUV(7) = JVS(7)*UV(1)+JVS(25)*UV(7)+JVS(32)*UV(8)+JVS(60)*UV(16)+JVS(76)*UV(17)
  JTUV(8) = JVS(16)*UV(2)+JVS(18)*UV(3)+JVS(20)*UV(4)+JVS(22)*UV(5)+JVS(24)*UV(6)+JVS(26)*UV(7)+JVS(33)*UV(8)+JVS(88)&
              &*UV(18)
  JTUV(9) = JVS(8)*UV(1)+JVS(35)*UV(9)+JVS(47)*UV(15)+JVS(62)*UV(16)+JVS(78)*UV(17)
  JTUV(10) = JVS(9)*UV(1)+JVS(37)*UV(10)+JVS(48)*UV(15)+JVS(63)*UV(16)+JVS(79)*UV(17)
  JTUV(11) = JVS(10)*UV(1)+JVS(39)*UV(11)+JVS(49)*UV(15)+JVS(64)*UV(16)+JVS(80)*UV(17)
  JTUV(12) = JVS(11)*UV(1)+JVS(41)*UV(12)+JVS(50)*UV(15)+JVS(65)*UV(16)+JVS(81)*UV(17)
  JTUV(13) = JVS(12)*UV(1)+JVS(43)*UV(13)+JVS(51)*UV(15)+JVS(66)*UV(16)+JVS(82)*UV(17)
  JTUV(14) = JVS(13)*UV(1)+JVS(45)*UV(14)+JVS(52)*UV(15)+JVS(67)*UV(16)+JVS(83)*UV(17)
  JTUV(15) = JVS(36)*UV(9)+JVS(38)*UV(10)+JVS(40)*UV(11)+JVS(42)*UV(12)+JVS(44)*UV(13)+JVS(46)*UV(14)+JVS(53)*UV(15)&
               &+JVS(89)*UV(18)
  JTUV(16) = JVS(14)*UV(1)+JVS(69)*UV(16)+JVS(85)*UV(17)+JVS(90)*UV(18)
  JTUV(17) = JVS(86)*UV(17)+JVS(91)*UV(18)
  JTUV(18) = JVS(34)*UV(8)+JVS(54)*UV(15)+JVS(92)*UV(18)
      
END SUBROUTINE JacTR_SP_Vec

! End of JacTR_SP_Vec function
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



END MODULE gckpp_Jacobian

