! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Parameter Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Parameters.f90
! Time                 : Sat Jul 25 22:40:36 2020
! Working directory    : /net/seasasfs02/srv/export/seasasfs02/share_root/vshah/Hg/GC_Hg/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Parameters

  USE gckpp_Precision
  PUBLIC
  SAVE


! NSPEC - Number of chemical species
  INTEGER, PARAMETER :: NSPEC = 30 
! NVAR - Number of Variable species
  INTEGER, PARAMETER :: NVAR = 19 
! NFLUX - Number of Reaction Flux species
  INTEGER, PARAMETER :: NFLUX = 1 
! NFAM - Number of Prod/Loss Families
  INTEGER, PARAMETER :: NFAM = 1 
! NVARACT - Number of Active species
  INTEGER, PARAMETER :: NVARACT = 17 
! NFIX - Number of Fixed species
  INTEGER, PARAMETER :: NFIX = 11 
! NREACT - Number of reactions
  INTEGER, PARAMETER :: NREACT = 64 
! NVARST - Starting of variables in conc. vect.
  INTEGER, PARAMETER :: NVARST = 1 
! NFIXST - Starting of fixed in conc. vect.
  INTEGER, PARAMETER :: NFIXST = 20 
! NONZERO - Number of nonzero entries in Jacobian
  INTEGER, PARAMETER :: NONZERO = 77 
! LU_NONZERO - Number of nonzero entries in LU factoriz. of Jacobian
  INTEGER, PARAMETER :: LU_NONZERO = 77 
! CNVAR - (NVAR+1) Number of elements in compressed row format
  INTEGER, PARAMETER :: CNVAR = 20 
! NLOOKAT - Number of species to look at
  INTEGER, PARAMETER :: NLOOKAT = 0 
! NMONITOR - Number of species to monitor
  INTEGER, PARAMETER :: NMONITOR = 0 
! NMASS - Number of atoms to check mass balance
  INTEGER, PARAMETER :: NMASS = 1 

! Index declaration for variable species in C and VAR
!   VAR(ind_spc) = C(ind_spc)

  INTEGER, PARAMETER :: ind_HGIICLp = 1 
  INTEGER, PARAMETER :: ind_HGIIORGp = 2 
  INTEGER, PARAMETER :: ind_HGBRNO2 = 3 
  INTEGER, PARAMETER :: ind_HGBRHO2 = 4 
  INTEGER, PARAMETER :: ind_HGBRCLO = 5 
  INTEGER, PARAMETER :: ind_HGBRBRO = 6 
  INTEGER, PARAMETER :: ind_HGBR2 = 7 
  INTEGER, PARAMETER :: ind_HGCLNO2 = 8 
  INTEGER, PARAMETER :: ind_HGCLHO2 = 9 
  INTEGER, PARAMETER :: ind_HGCLCLO = 10 
  INTEGER, PARAMETER :: ind_HGCLBRO = 11 
  INTEGER, PARAMETER :: ind_HGCLBR = 12 
  INTEGER, PARAMETER :: ind_HGBRO = 13 
  INTEGER, PARAMETER :: ind_HGBROH = 14 
  INTEGER, PARAMETER :: ind_HGBR = 15 
  INTEGER, PARAMETER :: ind_Hg0 = 16 
  INTEGER, PARAMETER :: ind_HGCLO = 17 
  INTEGER, PARAMETER :: ind_HGCL = 18 
  INTEGER, PARAMETER :: ind_HGCLOH = 19 

! Index declaration for fixed species in C
!   C(ind_spc)

  INTEGER, PARAMETER :: ind_Br = 20 
  INTEGER, PARAMETER :: ind_Cl = 21 
  INTEGER, PARAMETER :: ind_OH = 22 
  INTEGER, PARAMETER :: ind_NO2 = 23 
  INTEGER, PARAMETER :: ind_NO = 24 
  INTEGER, PARAMETER :: ind_O3 = 25 
  INTEGER, PARAMETER :: ind_HO2 = 26 
  INTEGER, PARAMETER :: ind_BrO = 27 
  INTEGER, PARAMETER :: ind_ClO = 28 
  INTEGER, PARAMETER :: ind_CO = 29 
  INTEGER, PARAMETER :: ind_CH4 = 30 

! Index declaration for fixed species in FIX
!    FIX(indf_spc) = C(ind_spc) = C(NVAR+indf_spc)

  INTEGER, PARAMETER :: indf_Br = 1 
  INTEGER, PARAMETER :: indf_Cl = 2 
  INTEGER, PARAMETER :: indf_OH = 3 
  INTEGER, PARAMETER :: indf_NO2 = 4 
  INTEGER, PARAMETER :: indf_NO = 5 
  INTEGER, PARAMETER :: indf_O3 = 6 
  INTEGER, PARAMETER :: indf_HO2 = 7 
  INTEGER, PARAMETER :: indf_BrO = 8 
  INTEGER, PARAMETER :: indf_ClO = 9 
  INTEGER, PARAMETER :: indf_CO = 10 
  INTEGER, PARAMETER :: indf_CH4 = 11 

END MODULE gckpp_Parameters

