! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Sparse Jacobian Data Structures File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_JacobianSP.f90
! Time                 : Sat Jul 25 22:40:36 2020
! Working directory    : /net/seasasfs02/srv/export/seasasfs02/share_root/vshah/Hg/GC_Hg/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_JacobianSP

  PUBLIC
  SAVE


! Sparse Jacobian Data


  INTEGER, PARAMETER, DIMENSION(77) :: LU_IROW = (/ &
       1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1, & ! index 1 - 12
       1,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  2, & ! index 13 - 24
       2,  2,  3,  3,  4,  4,  5,  5,  6,  6,  7,  7, & ! index 25 - 36
       8,  8,  9,  9, 10, 10, 11, 11, 12, 12, 13, 13, & ! index 37 - 48
      13, 13, 14, 14, 14, 15, 15, 15, 15, 15, 15, 15, & ! index 49 - 60
      16, 16, 16, 17, 17, 17, 17, 18, 18, 18, 18, 18, & ! index 61 - 72
      18, 18, 19, 19, 19 /)

  INTEGER, PARAMETER, DIMENSION(77) :: LU_ICOL = (/ &
       1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 14, & ! index 1 - 12
      19,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, & ! index 13 - 24
      14, 19,  3, 15,  4, 15,  5, 15,  6, 15,  7, 15, & ! index 25 - 36
       8, 18,  9, 18, 10, 18, 11, 18, 12, 18,  3,  4, & ! index 37 - 48
      13, 15, 13, 14, 15,  5,  6,  7, 13, 14, 15, 16, & ! index 49 - 60
      15, 16, 18,  8,  9, 17, 18, 10, 11, 12, 16, 17, & ! index 61 - 72
      18, 19, 17, 18, 19 /)

  INTEGER, PARAMETER, DIMENSION(20) :: LU_CROW = (/ &
       1, 14, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, & ! index 1 - 12
      47, 51, 54, 61, 64, 68, 75, 78 /)

  INTEGER, PARAMETER, DIMENSION(20) :: LU_DIAG = (/ &
       1, 14, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, & ! index 1 - 12
      49, 52, 59, 62, 66, 73, 77, 78 /)


END MODULE gckpp_JacobianSP

