! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
! 
! Utility Data Module File
! 
! Generated by KPP-2.2.4_gc symbolic chemistry Kinetics PreProcessor
!       (http://www.cs.vt.edu/~asandu/Software/KPP)
! KPP is distributed under GPL, the general public licence
!       (http://www.gnu.org/copyleft/gpl.html)
! (C) 1995-1997, V. Damian & A. Sandu, CGRER, Univ. Iowa
! (C) 1997-2005, A. Sandu, Michigan Tech, Virginia Tech
!     With important contributions from:
!        M. Damian, Villanova University, USA
!        R. Sander, Max-Planck Institute for Chemistry, Mainz, Germany
! 
! File                 : gckpp_Monitor.f90
! Time                 : Mon Jun 29 11:32:40 2020
! Working directory    : /n/home02/thackray/GC_working/KPP/Standard
! Equation file        : gckpp.kpp
! Output root filename : gckpp
! 
! ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~



MODULE gckpp_Monitor


  CHARACTER(LEN=15), PARAMETER, DIMENSION(38) :: SPC_NAMES = (/ &
     'PHg            ','HGBRNO2        ','HGBRHO2        ', & ! index 1 - 3
     'HGBRCLO        ','HGBRBRO        ','HGBR2          ', & ! index 4 - 6
     'HGBROH         ','HGBR           ','HGCLNO2        ', & ! index 7 - 9
     'HGCLHO2        ','HGCLCLO        ','HGCLBRO        ', & ! index 10 - 12
     'HGCLBR         ','HGCLOH         ','HGCL           ', & ! index 13 - 15
     'HGORG          ','HgP            ','Hg0            ', & ! index 16 - 18
     'Br             ','Cl             ','OH             ', & ! index 19 - 21
     'NO2            ','HO2            ','BrO            ', & ! index 22 - 24
     'ClO            ','JHGCLOH        ','JHGBR          ', & ! index 25 - 27
     'JHGAQ          ','O3             ','SO4            ', & ! index 28 - 30
     'BCPI           ','POA1           ','OCPI           ', & ! index 31 - 33
     'SALA           ','SALC           ','NIT            ', & ! index 34 - 36
     'NH4            ','DST1           ' /)

  INTEGER, DIMENSION(1) :: LOOKAT
  INTEGER, DIMENSION(1) :: MONITOR
  CHARACTER(LEN=15), DIMENSION(1) :: SMASS
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_0 = (/ &
     '         Hg0 + O3 --> HGBR                                                                          ', & ! index 1
     '        Hg0 + SO4 --> HGBR                                                                          ', & ! index 2
     '       Hg0 + BCPI --> HGBR                                                                          ', & ! index 3
     '       Hg0 + POA1 --> HGBR                                                                          ', & ! index 4
     '       Hg0 + OCPI --> HGBR                                                                          ', & ! index 5
     '       Hg0 + SALA --> HGBR                                                                          ', & ! index 6
     '       Hg0 + SALC --> HGBR                                                                          ', & ! index 7
     '        Hg0 + NIT --> HGBR                                                                          ', & ! index 8
     '        Hg0 + NH4 --> HGBR                                                                          ', & ! index 9
     '       Hg0 + DST1 --> HGBR                                                                          ', & ! index 10
     '         Hg0 + Br --> HGBR                                                                          ', & ! index 11
     '             HGBR --> Hg0                                                                           ', & ! index 12
     '        HGBR + Br --> Hg0                                                                           ', & ! index 13
     '       HGBR + NO2 --> HGBRNO2                                                                       ', & ! index 14
     '       HGBR + HO2 --> HGBRHO2                                                                       ', & ! index 15
     '       HGBR + ClO --> HGBRCLO                                                                       ', & ! index 16
     '       HGBR + BrO --> HGBRBRO                                                                       ', & ! index 17
     '        HGBR + Br --> HGBR2                                                                         ', & ! index 18
     '        HGBR + OH --> HGBROH                                                                        ', & ! index 19
     '     HGBR + JHGBR --> Hg0                                                                           ', & ! index 20
     '         Hg0 + Cl --> HGCL                                                                          ', & ! index 21
     '        HGCL + Cl --> Hg0                                                                           ', & ! index 22
     '       HGCL + NO2 --> HGCLNO2                                                                       ', & ! index 23
     '       HGCL + HO2 --> HGCLHO2                                                                       ', & ! index 24
     '       HGCL + ClO --> HGCLCLO                                                                       ', & ! index 25
     '       HGCL + BrO --> HGCLBRO                                                                       ', & ! index 26
     '        HGCL + Br --> HGCLBR                                                                        ', & ! index 27
     '        HGCL + OH --> HGCLOH                                                                        ', & ! index 28
     ' HGCLOH + JHGCLOH --> HGCL                                                                          ', & ! index 29
     'HGCLHO2 + JHGCLOH --> HGCL                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(30) :: EQN_NAMES_1 = (/ &
     'HGCLNO2 + JHGCLOH --> HGCL                                                                          ', & ! index 31
     'HGCLBRO + JHGCLOH --> HGCL                                                                          ', & ! index 32
     'HGCLCLO + JHGCLOH --> HGCL                                                                          ', & ! index 33
     ' HGCLBR + JHGCLOH --> HGCL                                                                          ', & ! index 34
     '    HGORG + JHGAQ --> Hg0                                                                           ', & ! index 35
     '      HgP + JHGAQ --> Hg0                                                                           ', & ! index 36
     '          HGBRHO2 --> PHg + HgP                                                                     ', & ! index 37
     '          HGBRNO2 --> PHg + HgP                                                                     ', & ! index 38
     '          HGBRBRO --> PHg + HgP                                                                     ', & ! index 39
     '          HGBRCLO --> PHg + HgP                                                                     ', & ! index 40
     '           HGBROH --> PHg + HgP                                                                     ', & ! index 41
     '            HGBR2 --> PHg + HgP                                                                     ', & ! index 42
     '            HGORG --> PHg + HgP                                                                     ', & ! index 43
     '          HGCLHO2 --> PHg + HgP                                                                     ', & ! index 44
     '          HGCLNO2 --> PHg + HgP                                                                     ', & ! index 45
     '          HGCLBRO --> PHg + HgP                                                                     ', & ! index 46
     '          HGCLCLO --> PHg + HgP                                                                     ', & ! index 47
     '           HGCLOH --> PHg + HgP                                                                     ', & ! index 48
     '           HGCLBR --> PHg + HgP                                                                     ', & ! index 49
     '          HGBRHO2 --> HGORG                                                                         ', & ! index 50
     '          HGBRNO2 --> HGORG                                                                         ', & ! index 51
     '          HGBRBRO --> HGORG                                                                         ', & ! index 52
     '          HGBRCLO --> HGORG                                                                         ', & ! index 53
     '           HGBROH --> HGORG                                                                         ', & ! index 54
     '            HGBR2 --> HGORG                                                                         ', & ! index 55
     '          HGCLHO2 --> HGORG                                                                         ', & ! index 56
     '          HGCLNO2 --> HGORG                                                                         ', & ! index 57
     '          HGCLBRO --> HGORG                                                                         ', & ! index 58
     '          HGCLCLO --> HGORG                                                                         ', & ! index 59
     '           HGCLOH --> HGORG                                                                         ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(7) :: EQN_NAMES_2 = (/ &
     '           HGCLBR --> HGORG                                                                         ', & ! index 61
     '          HGBRHO2 --> HGBR                                                                          ', & ! index 62
     '          HGBRNO2 --> HGBR                                                                          ', & ! index 63
     '           HGBROH --> HGBR                                                                          ', & ! index 64
     '          HGBRCLO --> HGBR                                                                          ', & ! index 65
     '          HGBRBRO --> HGBR                                                                          ', & ! index 66
     '            HGBR2 --> HGBR                                                                          ' /)
  CHARACTER(LEN=100), PARAMETER, DIMENSION(67) :: EQN_NAMES = (/&
    EQN_NAMES_0, EQN_NAMES_1, EQN_NAMES_2 /)

  CHARACTER(LEN=15), PARAMETER, DIMENSION(1) :: FAM_NAMES = (/ &
     'PHg            ' /)

! INLINED global variables

! End INLINED global variables


END MODULE gckpp_Monitor
